aikithoughts/aiki_blog/urls.py
from django.conf.urls import url

from .views.index_view import IndexView
from .views.post.post_detail_view import PostDetailView

app_name = 'aiki'

urlpatterns = [
    url(r'^$', IndexView.as_view(), name='index'),
    url(r'^post/(?P<pk>[0-9]+)/$', PostDetailView.as_view(), name='post_detail')
]

aikithoughts/aikithoughts/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^markdownx/', include('markdownx.urls')),
    url(r'', include('aiki_blog.urls')),
]

aikithoughts/aiki_blog/models/post.py
from django.db import models
from django.utils import timezone

from behavioralist.behaviors.excerptable import Excerptable
from behavioralist.querysets import PostQuerySet


class Post(Excerptable, models.Model):
    author = models.ForeignKey(to='auth.User')
    title = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(blank=True, null=True)

    objects = PostQuerySet.as_manager()

    def __str__(self):
        return self.title

    def publish(self):
        self.published_date = timezone.now()
        self.save()

aikithoughts/aiki_blog/views/index_view.py
from django.views.generic import ListView

from ..models import Post


class IndexView(ListView):
    context_object_name = 'posts'
    template_name = 'index.html'

    def get_queryset(self):
        return Post.objects.published().newest()

aikithoughts/aiki_blog/templates/_includes/favicon.html
{% load staticfiles %}

<!-- For IE 9 and below. ICO should be 32x32 pixels in size -->
<!--[if IE]><link rel="shortcut icon" href="{% static 'aiki_blog/img/favicon-32x32.png' %}"><![endif]-->

<!-- Touch Icons - iOS and Android 2.1+ -->
<link rel="apple-touch-icon-precomposed" type="image/png" sizes="180x180" href="{% static 'aiki_blog/img/favicon-180x180.png' %}">

<!-- Firefox, Chrome, Safari, IE 11+ and Opera -->
<link rel="icon" type="image/png" sizes="192x192" href="{% static 'aiki_blog/img/favicon-192x192.png' %}">

aikithoughts/aiki_blog/templates/_includes/header.html
{% load staticfiles %}

<header class="base-container">
  <div class="logo no-select">
    <a class="logo-text" href="{% url 'aiki:index' %}">
      <strong>Aiki</strong>
      <span>Thoughts</span>
    </a>
  </div>

  <div class="about-links text-center">
    <a href="javascript:void(0);">Về AikiThoughts</a>
    <span class="dot">&bull;</span>
    <a href="mailto:luan@tklarryonline.me">
      <img src="{% static 'aiki_blog/img/email-icon.png' %}" alt="Liên lạc"/>
    </a>
  </div>
</header>

aikithoughts/aiki_blog/templates/_layout/base.html
{% load compress %}
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <title>{% block title %}Aikithoughts{% endblock %}</title>

    {% include '_includes/favicon.html' %}

    <link href='https://fonts.googleapis.com/css?family=Roboto+Slab:400,300,700&subset=latin,vietnamese'
          rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:600&subset=latin,vietnamese' rel='stylesheet'
          type='text/css'>
    {% block css %}
      {% compress css %}
        <link rel="stylesheet" type="text/css" href="{% static 'aiki_blog/css/normalize.css' %}">
        <link rel="stylesheet" type="text/x-scss" href="{% static 'aiki_blog/css/base.scss' %}">
      {% endcompress %}
    {% endblock %}
  </head>
  <body>
    {% include '_includes/header.html' %}

    <div class="base-container">
      {% block content %}
      {% endblock %}
    </div>
  </body>
</html>

aikithoughts/aiki_blog/templates/index.html
{% extends '_layout/base.html' %}

{% load compress %}
{% load markdownx %}
{% load staticfiles %}

{% block title %}Home | {{ block.super }}{% endblock %}

{% block css %}
  {{ block.super }}
  {% compress css %}
    <link rel="stylesheet" type="text/x-scss" href="{% static 'aiki_blog/css/posts.scss' %}">
  {% endcompress %}
{% endblock %}

{% block content %}
<div class="posts-list">
  {% for post in posts %}
  <div class="post">
    <h1 class="post-title">
      <a href="{% url 'aiki:post_detail' pk=post.pk %}">{{ post.title}}</a>
    </h1>
    <div class="post-time">{{ post.published_date | date:'M j, Y, G:i' }}</div>
    <div class="post-content">{{ post.excerpt | markdownxify }}</div>
  </div>
  <hr class="circle-divider">
  {% empty %}
  No posts written yet.
  {% endfor %}
</div>
{% endblock %}

aikithoughts/aiki_blog/templates/post/detail.html
{% extends '_layout/base.html' %}

{% load compress %}
{% load markdownx %}
{% load staticfiles %}

{% block title %}{{ post.title }} | {{ block.super }}{% endblock %}

{% block css %}
  {{ block.super }}
  {% compress css %}
    <link rel="stylesheet" type="text/x-scss", href="{% static 'aiki_blog/css/posts.scss' %}">
  {% endcompress %}
{% endblock %}

{% block content %}
<div class="post">
  <h1 class="post-title">{{ post.title}}</h1>
  <div class="post-time">{{ post.published_date | date:'M j, Y, G:i' }}</div>
  <div class="post-content">{{ post.text | markdownxify }}</div>
</div>
{% endblock %}